export enum CategoryConstants {
  FoodAndDrink = 'food-drink',
  SportsAndFitness = 'sports-fitness',
  Technology = 'technology',
  BusinessAndProfessional = 'business-professional',
  General = 'general',
  ArtAndCulture = 'art-culture',
  MusicAndConcerts = 'music-concerts',
  EducationAndLearning = 'education-learning',
  CommunityAndSocial = 'community-social',
  HealthAndWellness = 'health-wellness',
  NetworkingAndEvents = 'networking-events',
  CharityAndNonprofits = 'charity-nonprofits',
  FilmAndCinema = 'film-cinema',
  LiteratureAndWriting = 'literature-writing',
  FashionAndStyle = 'fashion-style',
  TravelAndAdventure = 'travel-adventure',
}
